### ISSUE TITLE
Umbrella 1.0

### ISSUE THREAD

**Issue by ellbee** [faassen/reselect#37]
- [x] Variadic Dependencies #27 
- [x] Pass props into selectors #20
- [x] Way to shortcut evaluation #7
- [x] Customizable memoize function
- [x] Update Documentation #22, #34, #26
- [x] Lint task

Discussion here: #35
